FROM python:3
ENV APP /app
RUN mkdir $APP
WORKDIR $APP
EXPOSE 5000
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
RUN export FLASK_APP=run.py
RUN export FLASK_CONFIG=production
CMD [ "uwsgi", "--ini", "app.ini" ]